/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/review/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_review_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/accepted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accepted */
        get: operations["accepted_review_accepted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_review__flag_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_review__flag_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_review__flag_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit */
        post: operations["edit_review__flag_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review */
        get: operations["list_review_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Item */
        get: operations["get_review_item_review__flag_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investigate */
        post: operations["investigate_review__flag_id__investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{flag_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_review__flag_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pnl */
        get: operations["get_pnl_pnl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Variances */
        get: operations["get_variances_variances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pnl/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pnl View */
        get: operations["get_pnl_view_pnl_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variances/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Variances View */
        get: operations["get_variances_view_variances_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedCommentaryItem */
        AcceptedCommentaryItem: {
            /** Flag Id */
            flag_id: string;
            /** Reporting Line */
            reporting_line: string;
            /** Order */
            order: number;
            /** Text */
            text: string;
            /** Is Edited */
            is_edited: boolean;
            provenance: components["schemas"]["DraftProvenance"];
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Text */
            text: string;
            /**
             * Accepted Hypothesis
             * @default true
             */
            accepted_hypothesis: boolean;
        };
        /** ControllerInput */
        ControllerInput: {
            /** Input Id */
            input_id: string;
            /** Flag Id */
            flag_id: string;
            /** Text */
            text: string;
            /**
             * Accepted Hypothesis
             * @default true
             */
            accepted_hypothesis: boolean;
        };
        /** Draft */
        Draft: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Draft Id */
            draft_id: string;
            /** Flag Id */
            flag_id: string;
            /** Commentary */
            commentary: string;
            /** Evidence */
            evidence: components["schemas"]["GLEvidenceRow"][];
            /** Rendered Figures */
            rendered_figures: components["schemas"]["RenderedFigure"][];
            controller_input?: components["schemas"]["ControllerInput"] | null;
            provenance: components["schemas"]["DraftProvenance"];
            /** Llm Log Refs */
            llm_log_refs: string[];
            /**
             * Is Proposal
             * @default true
             * @constant
             */
            is_proposal: true;
        };
        /** DraftProvenance */
        DraftProvenance: {
            /** Flag Id */
            flag_id: string;
            /** Evidence Row Ids */
            evidence_row_ids: string[];
            /** Controller Input Id */
            controller_input_id?: string | null;
        };
        /** EditRequest */
        EditRequest: {
            /** Edited Text */
            edited_text: string;
        };
        /**
         * FigureSource
         * @enum {string}
         */
        FigureSource: "block1" | "gl" | "aggregate";
        /**
         * FlaggedVariance
         * @description Versioned PUBLIC CONTRACT consumed by Block 3 (the AI layer).
         *
         *     Decimal fields serialize as strings in JSON mode (Pydantic v2 default) to
         *     preserve exact precision across the block boundary. Do not change this shape
         *     without bumping ``schema_version`` and the committed JSON Schema.
         */
        FlaggedVariance: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Flag Id */
            flag_id: string;
            /** Reporting Line */
            reporting_line: string;
            line_type: components["schemas"]["LineType"];
            time_cut: components["schemas"]["TimeCut"];
            scenario_pair: components["schemas"]["ScenarioPair"];
            /** Current Value */
            current_value: string;
            /** Comparator Value */
            comparator_value: string;
            /** Abs Variance */
            abs_variance?: string | null;
            /** Pct Variance */
            pct_variance?: string | null;
            /** Pp Variance */
            pp_variance?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "favorable" | "unfavorable";
            /** Rule Id */
            rule_id: string;
            /** Abs Threshold */
            abs_threshold: string;
            /** Pct Threshold */
            pct_threshold: string;
            /** Pp Threshold */
            pp_threshold: string;
        };
        /**
         * FlaggedVarianceView
         * @description The Block 1 flag (all fields) PLUS Python-formatted display strings.
         */
        FlaggedVarianceView: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Flag Id */
            flag_id: string;
            /** Reporting Line */
            reporting_line: string;
            line_type: components["schemas"]["LineType"];
            time_cut: components["schemas"]["TimeCut"];
            scenario_pair: components["schemas"]["ScenarioPair"];
            /** Current Value */
            current_value: string;
            /** Comparator Value */
            comparator_value: string;
            /** Abs Variance */
            abs_variance?: string | null;
            /** Pct Variance */
            pct_variance?: string | null;
            /** Pp Variance */
            pp_variance?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "favorable" | "unfavorable";
            /** Rule Id */
            rule_id: string;
            /** Abs Threshold */
            abs_threshold: string;
            /** Pct Threshold */
            pct_threshold: string;
            /** Pp Threshold */
            pp_threshold: string;
            /** Current Display */
            current_display: string;
            /** Comparator Display */
            comparator_display: string;
            /** Abs Display */
            abs_display?: string | null;
            /** Pct Display */
            pct_display?: string | null;
            /** Pp Display */
            pp_display?: string | null;
        };
        /** GLEvidenceRow */
        GLEvidenceRow: {
            /** Transaction Id */
            transaction_id: string;
            /** Gl Account */
            gl_account: string;
            /** Amount */
            amount: string;
            /** Period */
            period: number;
            /** Scenario */
            scenario: string;
            /** Date */
            date: string;
            /** Project */
            project?: string | null;
            /** Counterparty */
            counterparty?: string | null;
            /**
             * Labels
             * @default []
             */
            labels: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hypothesis */
        Hypothesis: {
            /** Text */
            text?: string | null;
            /**
             * Evidence Row Ids
             * @default []
             */
            evidence_row_ids: string[];
        };
        /** InvestigationRecord */
        InvestigationRecord: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Flag Id */
            flag_id: string;
            variance: components["schemas"]["FlaggedVariance"];
            status: components["schemas"]["RecordStatus"];
            /** Evidence */
            evidence: components["schemas"]["GLEvidenceRow"][];
            hypothesis: components["schemas"]["Hypothesis"];
            question?: components["schemas"]["Question"] | null;
            draft?: components["schemas"]["Draft"] | null;
            /** Llm Log Refs */
            llm_log_refs: string[];
        };
        /**
         * LineType
         * @enum {string}
         */
        LineType: "revenue" | "cost" | "subtotal" | "margin";
        /** PnLCell */
        PnLCell: {
            /** Reporting Line */
            reporting_line: string;
            scenario: components["schemas"]["Scenario"];
            time_cut: components["schemas"]["TimeCut"];
            /** Value */
            value: string;
            value_kind: components["schemas"]["ValueKind"];
            /**
             * Is Margin
             * @default false
             */
            is_margin: boolean;
        };
        /** PnLLine */
        PnLLine: {
            /** Reporting Line */
            reporting_line: string;
            /** Order */
            order: number;
            line_type: components["schemas"]["LineType"];
            /** Cells */
            cells: components["schemas"]["PnLCell"][];
            /**
             * Display Label
             * @default
             */
            display_label: string;
        };
        /** PnLLineView */
        PnLLineView: {
            /** Reporting Line */
            reporting_line: string;
            /** Order */
            order: number;
            /** Line Type */
            line_type: string;
            /** Cells */
            cells: components["schemas"]["PnlCellView"][];
        };
        /** PnLResult */
        PnLResult: {
            /** Lines */
            lines: components["schemas"]["PnLLine"][];
            reconciliation: components["schemas"]["ReconciliationStatus"];
            provenance: components["schemas"]["ProvenanceIndex"];
            /**
             * Reporting Currency
             * @default EUR
             * @constant
             */
            reporting_currency: "EUR";
            /** Current Period */
            current_period: number;
        };
        /** PnLResultView */
        PnLResultView: {
            /** Lines */
            lines: components["schemas"]["PnLLineView"][];
            /** Reporting Currency */
            reporting_currency: string;
            /** Current Period */
            current_period: number;
        };
        /** PnlCellView */
        PnlCellView: {
            /** Reporting Line */
            reporting_line: string;
            /** Scenario */
            scenario: string;
            /** Time Cut */
            time_cut: string;
            /** Value */
            value: string;
            /** Display */
            display: string;
            /** Value Kind */
            value_kind: string;
            /** Is Margin */
            is_margin: boolean;
        };
        /**
         * ProvenanceIndex
         * @description Maps each cell to the contributing transaction ids.
         *
         *     Keyed by the string ``f"{reporting_line}|{scenario}|{time_cut}"`` so the model
         *     remains JSON-serializable while still giving full traceability for every cell
         *     (Constitution Principle II — Auditability).
         */
        ProvenanceIndex: {
            /**
             * By Cell
             * @default {}
             */
            by_cell: {
                [key: string]: string[];
            };
        };
        /** Question */
        Question: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Question Id */
            question_id: string;
            /** Flag Id */
            flag_id: string;
            /** Text */
            text: string;
            hypothesis: components["schemas"]["Hypothesis"];
            /** Evidence */
            evidence: components["schemas"]["GLEvidenceRow"][];
            /** Rendered Figures */
            rendered_figures: components["schemas"]["RenderedFigure"][];
            /** Llm Log Refs */
            llm_log_refs: string[];
        };
        /** ReconciliationStatus */
        ReconciliationStatus: {
            /** Is Complete */
            is_complete: boolean;
            /** Residual */
            residual: string;
            /**
             * Unmapped Accounts
             * @default {}
             */
            unmapped_accounts: {
                [key: string]: string;
            };
        };
        /**
         * RecordStatus
         * @enum {string}
         */
        RecordStatus: "question" | "draft";
        /** RenderedFigure */
        RenderedFigure: {
            /** Token */
            token: string;
            source: components["schemas"]["FigureSource"];
            /** Value */
            value: string;
            /** Origin */
            origin: string;
        };
        /** ReviewAction */
        ReviewAction: {
            /** Action Id */
            action_id: string;
            /** Flag Id */
            flag_id: string;
            /**
             * Current Period
             * @default 0
             */
            current_period: number;
            action: components["schemas"]["ReviewActionType"];
            /** Actor */
            actor: string;
            /** Ts */
            ts: string;
            from_status: components["schemas"]["ReviewStatus"];
            to_status: components["schemas"]["ReviewStatus"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ReviewActionType
         * @enum {string}
         */
        ReviewActionType: "investigate" | "answer" | "accept" | "edit" | "dismiss";
        /** ReviewItemView */
        ReviewItemView: {
            /** Flag Id */
            flag_id: string;
            /** Reporting Line */
            reporting_line: string;
            status: components["schemas"]["ReviewStatus"];
            record?: components["schemas"]["InvestigationRecord"] | null;
            original_draft?: components["schemas"]["Draft"] | null;
            controller_answer?: components["schemas"]["ControllerInput"] | null;
            /** Edited Text */
            edited_text?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** ReviewProgressView */
        ReviewProgressView: {
            /** Total */
            total: number;
            /** Resolved */
            resolved: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "detected" | "investigating" | "awaiting_controller" | "drafted" | "accepted" | "dismissed" | "failed";
        /**
         * Scenario
         * @enum {string}
         */
        Scenario: "prior_year" | "current_year" | "budget";
        /**
         * ScenarioPair
         * @enum {string}
         */
        ScenarioPair: "current_vs_prior_year" | "current_vs_budget";
        /**
         * TimeCut
         * @enum {string}
         */
        TimeCut: "prior_month_ytd" | "current_month" | "ytd" | "full_year";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueKind
         * @enum {string}
         */
        ValueKind: "actual" | "budget" | "landing" | "not_meaningful";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    progress_review_progress_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewProgressView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accepted_review_accepted_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedCommentaryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_review__flag_id__history_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewAction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_review__flag_id__accept_post: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_review__flag_id__dismiss_post: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_review__flag_id__edit_post: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_review_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_item_review__flag_id__get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_review__flag_id__investigate_post: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_review__flag_id__answer_post: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path: {
                flag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pnl_pnl_get: {
        parameters: {
            query: {
                current_period: number;
                time_cut?: components["schemas"]["TimeCut"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variances_variances_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlaggedVariance"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pnl_view_pnl_view_get: {
        parameters: {
            query: {
                current_period: number;
                time_cut?: components["schemas"]["TimeCut"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLResultView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variances_view_variances_view_get: {
        parameters: {
            query: {
                current_period: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlaggedVarianceView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
